## use makeCacheMatrix() to create an object containing a invertible matrix.
## e.g. testmatrix <- makeCacheMatrix(matrix(c(4,3,3,2),2,2))

## makeCacheMatrix has 4 methods, as follows:
## 	set: assigns a value to the matrix 
## 	get: reads the value of the matrix 
## 	setinv: assigns a value to the inverse matrix 
## 	getinv: reads the value of the inverse matrix 

## sample usage:
##
##	> test <- matrix(c(4,3,3,2),2,2); test
##	     [,1] [,2]
##	[1,]    4    3
##	[2,]    3    2
##	> doit <- makeCacheMatrix(test)
##	> cacheSolve(doit)
##	     [,1] [,2]
##	[1,]   -2    3
##	[2,]    3   -4


makeCacheMatrix <- function(x = matrix()) {
  xinv <- NULL ## clears the m variable on the environment
  set <- function(y) {
    x <<- y ## set the matrix as x
    xinv <<- NULL ## no inverse matrix calculation, m set as null
  }
  get <- function() x ## return the original matrix
  setinv <- function(inv) xinv <<- inv ## set the calculated inverse matrix in m
  getinv <- function() xinv ## get the inverse matrix
  list(set = set, get = get, ## creates a list of functions for this object 
       setinv = setinv,
       getinv = getinv)
}


## Returns a matrix that is the inverse of a matrix generated by makeCacheMatrix()

cacheSolve <- function(x, ...) {
  xinv <- x$getinv()
  if(!is.null(xinv)) { ## returns cached inverse value if there is one
    message("getting cached data")
    return(xinv)
  }
  data <- x$get() ## if not, calculates the inverse on the following lines
  xinv <- solve(data, ...)
  x$setinv(xinv)
  xinv ## returns the result
}